"""new mig

Revision ID: e0ac4398104c
Revises: 9c36d52dbcee
Create Date: 2025-02-26 10:45:55.981956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ac4398104c'
down_revision: Union[str, None] = '9c36d52dbcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'subtitle')
    # ### end Alembic commands ###
